sp = float(67.83643)
rj = float(36.67866)
mg = float(29.22988)
es = float(27.16548)
out = float(19.84953)
total = float(sp + rj + mg + es + out)
print(total)
porcentagemSP = ((sp/total)*100)
porcentagemRJ = ((rj/total)*100)
porcentagemMG = ((mg/total)*100)
porcentagemES = ((es/total)*100)
porcentagemOUT = ((out/total)*100)

print('Porcentagem de SP {:.2f}%'.format(porcentagemSP))
print('Porcentagem de RJ {:.2f}%'.format(porcentagemRJ))
print('Porcentagem de MG {:.2f}%'.format(porcentagemMG))
print('Porcentagem de ES {:.2f}%'.format(porcentagemES))
print('Porcentagem de Outros {:.2f}%'.format(porcentagemOUT))